# Site settings
title: Octopress themes
email: damir.svrtan@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I've gotten tired of looking at octopress themes in the way they're currently presented on octopress wiki:
  "https://github.com/imathis/octopress/wiki/3rd-Party-Octopress-Themes". Inspired by jekyllthemes, decided to make
  the same for octopress.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "octopressthemes.github.io" # the base hostname & protocol for your site
twitter_username: DamirSvrtan
github_username:  DamirSvrtan

# Build settings
markdown: kramdown
